# Generated by Django 4.2.30 on 2026-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('target_utilization', models.FloatField(default=85.0)),
                ('max_threshold', models.FloatField(default=95.0)),
                ('historical_baseline', models.FloatField(default=78.5)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=64, unique=True)),
                ('month_name', models.CharField(max_length=64)),
                ('horizon', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='J. Smith (Sr. Production Planner)', max_length=128)),
                ('status', models.CharField(default='Validated', max_length=32)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.CharField(default='4.8 MB', max_length=64)),
                ('processing_time_ms', models.IntegerField(default=1420)),
                ('months', models.JSONField(default=list)),
                ('departments', models.JSONField(default=dict)),
                ('validation_warnings', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
