# Generated by Django 4.2.30 on 2026-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningversion',
            name='chart_urls',
            field=models.JSONField(default=dict),
        ),
    ]
