# Generated by Django 4.2.30 on 2026-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningversion_chart_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInputConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(default='default_user', max_length=64, unique=True)),
                ('year', models.IntegerField(default=2026)),
                ('tasks', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
