# Generated by Django 4.2.30 on 2026-08-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_manualinputconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('project_number', models.CharField(max_length=128, unique=True)),
                ('equipment_name', models.CharField(blank=True, default='', max_length=256)),
                ('equipment_weight', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('zero_date', models.DateField(blank=True, null=True)),
                ('cdd', models.DateField(blank=True, null=True)),
                ('project_manager', models.CharField(blank=True, default='', max_length=128)),
                ('total_planned_hours', models.FloatField(default=0.0)),
                ('priority', models.CharField(default='Medium', max_length=32)),
                ('status', models.CharField(default='Planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('task_code', models.CharField(default='welding', max_length=64)),
                ('allocated_hours', models.FloatField(default=0.0)),
                ('duration_months', models.IntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('smi', models.CharField(blank=True, default='', max_length=128)),
                ('labour_supply', models.CharField(blank=True, default='', max_length=128)),
                ('job_contractor', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskMonthlyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.IntegerField(default=1)),
                ('month_label', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('hours', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_distributions', to='planning.projecttask')),
            ],
            options={
                'ordering': ['month_index'],
            },
        ),
    ]
