# Generated by Django 4.2.30 on 2026-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_project_projecttask_projecttaskmonthlydistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='actual_utilized_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='adjustment_month_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='buffer_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='buffer_month_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttaskmonthlydistribution',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttaskmonthlydistribution',
            name='is_buffer_added',
            field=models.BooleanField(default=False),
        ),
    ]
