# Generated by Django 4.2.30 on 2026-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_project_location_capacityadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='wbs_no',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
