# Generated by Django 4.2.30 on 2026-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_capacityplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fabrication_weight',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
