# Generated by Django 4.2.30 on 2026-08-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_project_edd_project_fabrication_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
