# Generated by Django 4.2.30 on 2026-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='so_line_items',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='so_no',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
